package com.vendora.epic1.model.enums;

public enum District {
    COLOMBO, GAMPAHA, KALUTARA, KANDY, MATALE, NUWARA_ELIYA,
    GALLE, MATARA, HAMBANTOTA, JAFFNA, KILINOCHCHI, MANNAR,
    MULLAITIVU, VAVUNIYA, TRINCOMALEE, BATTICALOA, AMPARA,
    KURUNEGALA, PUTTALAM, ANURADHAPURA, POLONNARUWA,
    BADULLA, MONARAGALA, RATNAPURA, KEGALLE
}